dist: xenial
language: python

python:
  - '3.8'

before_install:
  if ! [ -f ./src/GRCh37.tar.gz ]; then
    wget ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator/GRCh37.tar.gz -P ./src/;
  fi

install:
  - pip install .

cache:
  directories:
    - $TRAVIS_BUILD_DIR/src/
  branch:
    - master

before_script:
  - SigProfilerMatrixGenerator install -l $TRAVIS_BUILD_DIR/src/ GRCh37

script:
  - python3 tests/spt_test.py